### ISSUE TITLE
Error running LEVIATHAN (robin_hood::map overflow)

### ISSUE THREAD

**Issue by LucaBertoli** [morispi/LEVIATHAN#4]
Hi,
I was trying out LEVIATHAN for calling variants on a .bam file produced with LongRanger on linked-reads fastq files (TELL-seq technology). I have successfully built the LRez barcode indexes, but when I run LEVIATHAN, this is the output:

```
Preparing auxiliary data
Loading the barcodes positions index
Computing the number of common barcodes between all the pairs of regions of the genome
Processing barcodes, iteration 1 of 10

Processing barcodes, iteration 2 of 10

Processing barcodes, iteration 3 of 10

Processing barcodes, iteration 4 of 10

Processing barcodes, iteration 5 of 10

Processing barcodes, iteration 6 of 10

Processing barcodes, iteration 7 of 10

Processing barcodes, iteration 8 of 10

Processing barcodes, iteration 9 of 10

Processing barcodes, iteration 10 of 10

Computing and analyzing the distribution of shared barcodes between candidates
Removing invalid candidates (regions pairs that share do not share a sufficient number of barcodes and regions that are paired with more than 1000 other regions)
Saving all SV candidates to file "candidates.bedpe"
Number of valid SV candidates to consider : 276419

terminate called after throwing an instance of 'std::overflow_error'
  what():  robin_hood::map overflow
Aborted (core dumped)
```

Any idea why?
Thank you in advance,
Luca

**Comment by anne-gcd** [comment]
Hi @LucaBertoli,

I'm sorry to hear that you have a problem running LEVIATHAN. 

This error already occurred in the past (see closed issue #3) and we corrected it. The problem was that a hash table was not purged and kept to much memory.

That's why I'm surprised you are facing this issue. Which version of LEVIATHAN are you using ? What is you command line ? 

Best, 
Anne

**Comment by LucaBertoli** [comment]
I downloaded it yesterday and am currently using version v.1.0, maybe 1.0.1 fixes this problem. 

the command line is:
`/opt/LEVIATHAN/bin/LEVIATHAN -b possorted_bam.bam -i barcodeIndex.bci -g /home/db/hg38/Homo_sapiens_assembly38.fasta -o T511_output.vcf`

**Comment by anne-gcd** [comment]
Hi, 

The bug was fixed in the latest commit, but it's not included in the release of the version v1.0.1. 
Until a new release is done (it should be done very soon), I recommend you to install LEVIATHAN from source, using `git clone` (see README). 

Please let me know if this solves your problem.

Best,
Anne

**Comment by LucaBertoli** [comment]
I tried installing it with `git clone --recursive https://github.com/morispi/LEVIATHAN` and then `./install.sh` but the error remains... 

let me know if there is another way of installing it (I'm new on github)

Thank you,
Luca

**Comment by anne-gcd** [comment]
Hi Luca, 

First, I'd advise you to try out LEVIATHAN on the example dataset (see section "Getting started" of the README), to make sure LEVIATHAN has been installed properly. 

Then, if you have a big dataset with a good coverage, it's possible that you need a lot of RAM to run LEVIATHAN. How much RAM and how many CPUs did you use ? 

You can try running LEVIATHAN with 200G-300G RAM (and leave the number of threads to 8 by default). I'd suggest you also to increase the number of iterations (to avoid memory overflow), setting B to 100 (`-B 100`). You can also try with higher region sizes, setting r to 10000 (`-r 10000`).

Please let me know if doing that, LEVIATHAN runs without error. 

Best, 
Anne

**Comment by sav0016** [comment]
Dear @anne-gcd,

I have the same error as @LucaBertoli (without "Aborted (core dumped)" at the end). I have very large data (approx 325GB BAM file - 10x Genomics format from LongRanger). I have enough RAM memory on computational server (7TB). Should I also try to use -r 10000 parameter? But I'm looking for all structural variants so can I also set -v 50? Is this also somehow influenced by threads parameter?

Or what could help me solve this error.

Thank you very much
Best
Jakub

**Comment by anne-gcd** [comment]
Hi @sav0016,

Sorry for the late reply. 

First, I would like to know which version of LEVIATHAN are you using ? I recommend you to install LEVIATHAN from source, using git clone (see README).

Then, as you have very large data, I recommend you to try running LEVIATHAN with `-r 10000` and `-B 100`. 
You can try leaving the number of threads to 8 by default to begin with, but if it doesn't work, you can try increasing it (especially if you have enough allocated RAM). 
What is the coverage of your data ? 

Besides, if you're looking for all SVs, you should set `-v 50` indeed. 

I hope this solves your problem. If no, please let me know and we'll try to find a solution.

Best, 
Anne

**Comment by sav0016** [comment]
Hi @anne-gcd ,

Thank you very much!

I tried using B10 r10000 v50 and B20 r5000 v50 and it worked. I installed from source although -v still shows v1.0 ... Average coverage is about 100X. If I set v50 and r10000 it will find about 3000 SVs. If I set v50 and r5000 it will find about 9000 SVs. And also many SVs have SVLEN=1. I have about 720CPU and 7TB RAM available.

Best,
Jakub
